//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAP.Nova.UW.RateCalculatorService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUWProdProgRate
    {
        public int id { get; set; }
        public string szProduct { get; set; }
        public decimal dblProductRate { get; set; }
        public string szProgram { get; set; }
        public decimal dblProgRateAdj { get; set; }
        public System.DateTime dtPeriodStartDate { get; set; }
        public System.DateTime dtPeriodEndDate { get; set; }
    }
}
